### ISSUE TITLE
how to navigate other pug files ?

### ISSUE THREAD

**Issue by ourfamilygithub** [Giulico/ukyo#1]
Hey thanks you for creating this useful boilerplate
i am trying to navigate other pug files but the server response me `/GET Not Found`
how could we mention url in `<a href="">`

Thanks

**Comment by Giulico** [comment]
Hi,
Add the new pug file into /pug/ folder (es. `/src/pug/new-page.pug`)

Now you can reference the new page like this:
```
    a(href="/new-page.html") A new page
```

To make it work, you need to start the watcher again (`npm start`).

**Comment by ourfamilygithub** [comment]
@Giulico It works very well 
if you could please try update or add feature to this precious boilerplate

Thank you

**Comment by RexHung0302** [comment]
Hi,
thanks for created this useful project. 
I recently try to use webpack for translate pug to HTML,
but I got some troubles.

If I download your project should I create a new file webpack.config.js by myself?
Because I can't run the project.

Thanks for the update on the issue.

**Comment by Giulico** [comment]
Sorry for the late reply.
No, you don't need to create a new webpack config. This boilerplate works out of the box.
Just install the dependencies then run `yarn start`.
